[[plugins]] # 補完系プラグイン
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
	source ~/.config/nvim/plugins/coc.rc.vim
'''

[[plugins]] # ランナー系プラグイン
repo = 'thinca/vim-quickrun'
hook_add = '''
	source ~/.config/nvim/plugins/quickrun.rc.vim
'''

[[plugins]] # 非同期実行
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # オープンブラウザー
repo = 'tyru/open-browser.vim'

[[plugins]] # ファインダー系プラグイン
repo = 'Shougo/denite.nvim'
hook_add = '''
	source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]] # スタート画面カスタマイズ
repo = 'mhinz/vim-startify'

[[plugins]] # ステータスライン拡張
repo = 'itchyny/lightline.vim'
hook_add = '''
	source ~/.config/nvim/plugins/lightline.rc.vim
	'''

[[plugins]] # ファイラー系プラグイン
repo = 'Shougo/defx.nvim'
hook_add = '''
	source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]] # 括弧編集系プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # ウィンドウサイジング
repo = 'simeji/winresizer'

[[plugins]] # バイナリエディター
repo = 'Shougo/vinarise.vim'
hook_add = '''
	source ~/.config/nvim/plugins/vinarise.rc.vim
'''


# Git系プラグイン#############
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

############################


# 装飾系プラグイン#############
[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'
hook_add = '''
	source ~/.config/nvim/plugins/iceberg.rc.vim
'''

[[plugins]] # iconセット
repo = 'ryanoasis/vim-devicons'

[[plugins]] # defxIcon
repo = 'kristijanhusak/defx-icons'

[[plugins]] # インデント可視化
repo = 'Yggdroot/indentLine'
hook_add = '''
	source ~/.config/nvim/plugins/indentLine.rc.vim
'''

[[plugins]] # 空白可視化
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
	source ~/.config/nvim/plugins/vim-trailing-whitespace.rc.vim
'''

[[plugins]] # 多言語パック
repo = 'sheerun/vim-polyglot'
hook_add = '''
	source ~/.config/nvim/plugins/vim-polyglot.rc.vim
'''

[[plugins]] # タグリスト表示
repo = 'preservim/tagbar'
hook_add = '''
	source ~/.config/nvim/plugins/tagbar.rc.vim
'''

[[plugins]] # テンプレート生成
repo = 'mattn/vim-sonictemplate'
############################


# その他のプラグイン##########
[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]] # markdown preview
repo = 'previm/previm'
hook_add = '''
	source ~/.config/nvim/plugins/previm.rc.vim
'''
############################
